# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "koekeishiya/formulae"

# Binaries
brew "bash"
brew "bat"
brew "btop"
brew "coreutils"
brew "exa"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "grep"
brew "htop"
brew "httpie"
brew "mackup"
brew "mas"
brew "pinentry-mac"
brew "python@3.9"
brew "rclone"
brew "rmlint"
brew "stow"
brew "tmux"
brew "trash"
brew "tree"
brew "virtualenvwrapper"
brew "zoxide"
brew "jakehilborn/jakehilborn/displayplacer"

# Casks
cask "1password"
cask "adguard"
cask "appcleaner"
cask "arc"
cask "backblaze"
cask "command-tab-plus"
cask "cron"
cask "devonthink"
cask "flux"
cask "hazel"
cask "iina"
cask "iterm2"
cask "little-snitch"
cask "maccy"
cask "macmediakeyforwarder"
cask "mactex-no-gui"
cask "nordvpn"
cask "obsidian"
cask "postman"
cask "raycast"
cask "rectangle-pro"
cask "rocket"
cask "setapp"
cask "sigmaos"
cask "soundsource"
cask "tailscale"
cask "telegram"
cask "transmit"
cask "visual-studio-code"
cask "zoom"

# Fonts
cask "font-fira-code"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-junction"
cask "font-latin-modern"
cask "font-lato"
cask "font-open-sans"
cask "font-raleway"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-sans-pro"
cask "font-source-serif-pro"

# Mac App Store
mas '1Password for Safari', id: 1569813296
mas 'Crouton: Cooking Companion', id:1461650987
mas 'DaisyDisk', id:411643860
mas 'Data Jar', id:1453273600
mas 'Eat the Shorts for Safari', id: 1668012393
mas 'Focused Work - Pomodoro Timer', id: 1523968394
mas 'GoodNotes 5', id: 1444383602
mas 'Logger for Shortcuts', id: 1611554653
mas 'NextDNS', id:1464122853
mas 'Parcel - Delivery Tracking', id: 639968404
mas 'Raivo Receiver', id:1498497896
mas 'Sleeve for Spotify, Music', id:1606145041
mas 'Timery for Toggl', id: 1425368544
mas 'Vimari', id: 1480933944
mas 'WaterMinder - Water Tracker', id: 1415257369
mas 'Xcode', id:497799835