#!/usr/bin/env bash


# Ask for the administrator password upfront
sudo -v

# Updating all the things
sudo apt-get update; sudo apt-get upgrade

source .apt
source .stow

# Installing OMZ
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"